server:
  port: 8080
spring:
  datasource:
    druid:
      mysql:
        username: root
        password: mysql123
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://pig-mysql:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        initialSize: 5
        minIdle: 5
        maxActive: 20
      mongodb:
        username: root
        password: mysql123
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://pig-mysql:3306/sys?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        initialSize: 5
        minIdle: 5
        maxActive: 20
  security:
    user:
      name: angel
      password: angel
security:
  oauth2:
    client:
      id: angel_client_id
      client-id: angel_client_id
      client-secret: angel_client_secret
      scope:
      - server
logging:
  level:
    root: debug
    
     
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.pingan.angel.admin.entity
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://angel:angel@pig-eureka:8123/eureka/