server:
  port: 8125

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
 # 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://angel:angel@pig-eureka:8123/eureka/   
    
spring:
  application:
      name: angel-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      discovery:
        locator:
          enabled: true
      routes:
      # 认证中心
      - id: pig-auth
        uri: lb:/angel-auth #  重点！/info必须使用http进行转发，lb代表从注册中心获取服务
        predicates: #重点！转发该路径！,/auth/**,
        - Path=/auth/**
        filters:
          # 验证码处理
        - ValidateCodeGatewayFilter
          # 前端密码解密
        - PasswordDecoderFilter
      #UPMS 模块
      - id: pig-upms
        uri: lb://pig-upms
        predicates:
        - Path=/admin/**
        filters:
          # 限流配置
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
          # 降级配置
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback'
      
