server:
  port: 8126
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

spring:
  application:
    name: angel-quartz
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://pig-mysql:3306/sys?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql123


eureka:
  client:
    service-url:
      defaultZone: http://angel:angel@localhost:8123/eureka/
      
